spring:
  profiles: 
  #此属性配置选择的配置环境，优先级高于pom文件的默认指定
    active: test
  mvc:
    view:
      #视图解析，页面存放目录及后缀
      prefix: /ui/
      suffix: .html
#分页插件 pagehelper   
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#mybatis配置
mybatis:
  #自定义resultType
  typeAliasesPackage: hk.zcb.userModule.dao.entity
  #mapper路径
  mapperLocations: classpath:mapper/*.xml
  #mybatis配置文件路径
  configLocation: classpath:/mybatis-config.xml
#配置信息
#emailConfig:
  #收信人,多个收信人用逗号分隔
#  to: hkzcb2018@163.com,hkzcb2017@163.com
  #发信人,需要在邮件账号中开启POP3/SMTP服务
#  from: 348437667@qq.com
  #发信人授权码
#  authorizationCode: cwohnwyxtklzcbcg
  #邮件服务器
#  emailServer: smtp.qq.com
  #邮件协议,只测试了smtp
#  mailProtocol: smtp
  #邮件标题
#  mailTitle: javaMail测试发送111
  #邮件内容
#  mailMainBody: 测试邮件
  
